name: Reddit Meme

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '1 * * * *'

jobs:
  deploy:
    name: Update Reddit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Reddit
        uses: d3code/github-action-readme-reddit-meme@latest
        with:
         commit_author: GitHub Actions
         commit_email: github-actions[bot]@users.noreply.github.com
