name: Build  #Definimos el nombre del flujo de trabajo, en este caso Build

on:  # En la rama main es donde se desencadenara todo lo siguiente
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs: # aqui empieza todo lo que se har치 en el YAML
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest  # en estas tres lineas se corre una maquina ubuntu, en su ultima versi칩n

    env:
      NODE_VERSION: 20  # en este caso se usa Node, en su version 20

    steps:  # Aqui se definen los pasos que se llevaran a cabo 
      - uses: actions/checkout@v4.1.1  # en este paso se clona el repositorio
        with:
          fetch-depth: 0 

      - name: Setup Node.js
        run: |  # en este paso la maaquina ubuntu actualiza los paquetes, instala nodejs y npm, ademas de mostrar sus versiones
          sudo apt-get update  # Actualiza los paquetes del sistema
          sudo apt-get install -y nodejs npm  # Instala Node.js y npm
          node -v  # Muestra la versi칩n de Node.js instalada
          npm -v  # Muestra la versi칩n de npm instalada

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master  # Por ultimo se realiza el escaneo, requiriendo las variables de entorno de
        # github y sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
