name: test-html-validate
on:
  pull_request:
    types:
    - assigned
    - opened
    - synchronize
    - reopened
  push:
    branches:
    - main
jobs:
  build-unminified-site:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: "Build site audit"
      uses: IsraC0d33/Proyecto1Marcas@main
      with:
        base-url: "https://israc0d33.github.io/Proyecto1Marcas/"
        build-for-downstream: "true"
        source-directory: ./index.html
        use-lfs: false
    - name: "Validate HTML of statically generated website"
      uses: wildtechgarden/validator-html-action@main
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        use-existing-workspace: "true"
